applications:
- name: daytrader-ee6
  memory: 512M
  disk_quota: 1024M
  instances: 1
  host: <unique_sub_domain>
  domain: mybluemix.net
  env: 
    DAYTRADER3_CONTEXT_ROOT_URL: "https://<unique_sub_domain>.mybluemix.net/daytrader"
    